### ISSUE TITLE
punten score not fitting in progress bar on all display sizes

### ISSUE THREAD

**Issue by LewisVdC** [Maarten-buelens/schoolware_api_ui#1]
in the points screen the scores dont fit in the bar on larger screens (or all idk), can be fixed by adding 

`height:auto;`

to the following css elements

`.progress-bar-bad`
`.progress-bar-good`
`.progress`

**Comment by LewisVdC** [comment]
![image](https://github.com/Maarten-buelens/schoolware_api/assets/95618898/c74757b2-7a9e-4b37-a00b-e1a75200443e)
image of broken css

**Comment by Maarten-buelens** [comment]
I tried on a larger screen and it was correct for me. But i added it anyway.
Could you if it is now fixed?

**Comment by LewisVdC** [comment]
![image](https://github.com/Maarten-buelens/schoolware_api_ui/assets/95618898/176d8a09-0748-4d1b-9421-2decaa2a9c83)
fixed! thanks.
